// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypadqfjnontdlujnpmsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwYWRxZmpub250ZGx1am5wbXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDYzNTksImV4cCI6MjA2MjM4MjM1OX0.aDsNLBvh_u0rS1rnjqF4fMcyWhch68SZ5mlheW1uIPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);